# -*- coding: utf-8 -*-
"""caso3_produccion_ejercicio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-i8kyl_4MHqbKFewP0AhUNvPCnI8wuZ

# 🏭 CASO 3 — PRODUCCIÓN
## Visualización de Datos con Streamlit
### Notebook de Ejercicio — ¡Completa el código!

---

**Empresa:** MetalParts Manufacturing  
**Contexto:** MetalParts es una planta de manufactura de piezas metálicas con 4 líneas de producción. El área de operaciones necesita un dashboard para monitorear la eficiencia de producción, identificar las principales causas de paro, y controlar la tasa de defectos por línea y turno.

**Tu misión:** Completar los espacios marcados con `# ??? COMPLETAR` para construir el análisis completo.

---
> 📖 **Patrón de lectura F:** Lee el enunciado de cada celda, luego el código existente, luego enfócate en los comentarios `# ???`

## 📦 PASO 1 — Importar librerías
"""

#pip install streamlit

# ??? COMPLETAR: Importa las librerías necesarias
# Pista: pandas (como pd), plotly.express (como px), numpy (como np)

import streamlit as st
import pandas as pd        # ??? pandas
import plotly.express as px        # ??? plotly.express
import numpy as np        # ??? numpy
import plotly.graph_objects as go

print('✅ Librerías importadas correctamente')

"""## 📊 PASO 2 — Cargar el dataset"""

# Cargar el dataset de producción
# ??? COMPLETAR: Usa pd.read_csv() para leer 'caso3_produccion_dataset.csv'
df = pd.read_csv('caso3_produccion_dataset (1).csv')

# ??? COMPLETAR: Convierte 'fecha_produccion' a tipo datetime
# Pista: usa pd.to_datetime()
df['fecha_produccion'] = pd.to_datetime(df['fecha_produccion'])

# Mostrar información básica del DataFrame

print(f'Total registros: {len(df)}')
print(f'Columnas disponibles: {list(df.columns)}')
df.head()

"""## 📈 PASO 3 — Exploración básica"""

# Estadísticas descriptivas del dataset
# ??? COMPLETAR: Muestra estadísticas descriptivas del DataFrame
# Pista: usa el método .describe()
print('📈 Estadísticas descriptivas:')
df.describe().round(2)

# ── KPI 1: Eficiencia promedio y unidades producidas ───────────
total_unidades = df['unidades_producidas'].sum()

# ??? COMPLETAR: Calcula la eficiencia promedio de 'eficiencia_pct'
# Pista: usa .mean()
eficiencia_promedio = df['eficiencia_pct'].mean()

# ??? COMPLETAR: Calcula el total de unidades defectuosas
total_defectuosas = len(df['unidades_defectuosas'])

print(f'📦 Unidades producidas: {total_unidades:,}')
print(f'⚙️ Eficiencia promedio: {eficiencia_promedio:.1f}%')
print(f'❌ Unidades defectuosas: {total_defectuosas:,}')

# ── KPI 2: Eficiencia por línea de producción ──────────────────
# ??? COMPLETAR: Agrupa por 'linea_produccion' y calcula:
#   - eficiencia promedio
#   - total unidades producidas
#   - total unidades defectuosas
# Pista: usa .groupby().agg() con 'mean' y 'sum'

eficiencia_linea = (
    df.groupby('linea_produccion')
      .agg(
          eficiencia_promedio=('eficiencia_pct', 'mean'),      # ??? promedio
          unidades_producidas=('unidades_producidas', 'sum'), # ??? suma
          unidades_defectuosas=('unidades_defectuosas', 'sum') # ??? suma
      )
      .round(2)
      .reset_index()
)

print('🏭 Eficiencia por línea:')
eficiencia_linea

# ── KPI 3: Tiempo de paro por causa ───────────────────────────
# ??? COMPLETAR: Agrupa por 'causa_paro' y suma 'tiempo_paro_min'
# Luego ordena de mayor a menor

paros_causa = (
    df.groupby('causa_paro')
      .agg(
          tiempo_total_min=('tiempo_paro_min', 'sum'),  # ??? suma
          num_paros=('id_orden', 'count')
      )
      .sort_values('tiempo_total_min', ascending=False)              # ??? ordena por tiempo_total_min
      .reset_index()
)

print('⏱️ Tiempo de paro por causa:')
paros_causa

"""## 📉 PASO 4 — Visualizaciones con Plotly

Recuerda la estructura básica:
```python
fig = px.tipo_grafica(df, x='col_x', y='col_y', title='Título')
fig.show()
```
"""

# ── Gráfica 1: Barras — Eficiencia promedio por línea ──────────
# ??? COMPLETAR: Crea un gráfico de barras verticales
# x = linea_produccion, y = eficiencia_promedio
# Pista: px.bar() sin orientation (vertical por defecto)

fig1 = px.bar(
    eficiencia_linea,
    x='linea_produccion',                           # ??? columna de línea
    y='eficiencia_promedio',                           # ??? columna de eficiencia
    title='⚙️ Eficiencia Promedio por Línea de Producción',
    labels={'linea_produccion': 'Línea', 'eficiencia_promedio': 'Eficiencia (%)'},
    color='eficiencia_promedio',
    color_continuous_scale='RdYlGn',
    text_auto=True
)

fig1.show()

# ── Gráfica 2: Pie — Distribución de causas de paro ───────────
# ??? COMPLETAR: Crea un gráfico de torta para causas de paro
# Pista: px.pie(df, names='columna_categorias', values='columna_valores')

fig2 = px.pie(
    paros_causa,
    names='causa_paro',                        # ??? columna de causas
    values='tiempo_total_min',                       # ??? columna de tiempo total
    title='⏱️ Distribución del Tiempo de Paro por Causa',
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig2.show()

# ── Gráfica 3: Serie de tiempo — Eficiencia mensual ───────────
eficiencia_mes = df.groupby(df['fecha_produccion'].dt.to_period('M'))['eficiencia_pct'].mean().reset_index()
eficiencia_mes['fecha_produccion'] = eficiencia_mes['fecha_produccion'].astype(str)

# ??? COMPLETAR: Crea un gráfico de líneas para la evolución mensual
# Pista: px.line() con markers=True para ver los puntos

fig3 = px.line(
    eficiencia_mes,
    x='fecha_produccion',
    y='eficiencia_pct',
    markers=True,                      # ??? True para mostrar puntos
    title='📅 Evolución Mensual de Eficiencia (%)',
    labels={'fecha_produccion': 'Mes', 'eficiencia_pct': 'Eficiencia (%)'}
)

fig3.show()

# ── Gráfica 4: Scatter — Tiempo de paro vs Tasa de defectos ───
# ??? COMPLETAR: Crea un scatter plot tiempo_paro_min vs tasa_defectos_pct
# Usa color='linea_produccion' y hover_data=['producto', 'turno', 'maquina']

fig4 = px.scatter(
    df,
    x='tiempo_paro_min',                           # ??? tiempo de paro
    y='tasa_defectos_pct',                           # ??? tasa de defectos
    color='linea_produccion',                       # ??? color por línea de producción
    hover_data=['producto', 'turno', 'maquina'],
    title='🔍 Tiempo de Paro vs Tasa de Defectos',
    labels={
        'tiempo_paro_min': 'Tiempo de Paro (min)',
        'tasa_defectos_pct': 'Tasa de Defectos (%)'
    }
)

fig4.show()

# ── Gráfica 5: Heatmap — Eficiencia por línea y turno ─────────
# ??? COMPLETAR: Crea la tabla pivote y el heatmap
# Pista:
#   pivot = df.pivot_table(values='eficiencia_pct', index='linea_produccion',
#                          columns='turno', aggfunc='mean')
#   fig = px.imshow(pivot, ...)

pivot_linea_turno = df.pivot_table(
    values='eficiencia_pct',                      # ??? eficiencia_pct
    index='linea_produccion',                       # ??? linea_produccion
    columns='turno',                     # ??? turno
    aggfunc='mean'
).round(1)

fig5 = px.imshow(
    pivot_linea_turno,
    title='🌡️ Eficiencia Promedio por Línea y Turno (%)',
    color_continuous_scale='Blues',      # ??? elige: 'RdYlGn', 'Blues', 'Viridis'
    text_auto=True
)

fig5.show()

"""## 🌐 PASO 5 — App Streamlit

Una vez que tus gráficas funcionen en el notebook, ejecuta la app completa:

```bash
streamlit run caso3_produccion_app.py
```

### 🧩 Desafío extra
En el archivo `caso3_produccion_app.py`, agrega filtros en el sidebar para:
- Filtrar por `turno` (Mañana / Tarde / Noche)
- Filtrar por `linea_produccion`
- Mostrar solo órdenes con `eficiencia_pct < 70` como alerta de baja eficiencia
"""

# ── DESAFÍO: Órdenes con baja eficiencia ──────────────────────
# ??? COMPLETAR: Filtra el DataFrame para mostrar órdenes con
# eficiencia_pct menor a 70 y tasa_defectos_pct mayor a 5

baja_eficiencia = df[
    (df['eficiencia_pct'] < 0.70) &       # ??? 70%
    (df['tasa_defectos_pct'] > 0.50)       # ??? 5%
][['id_orden', 'linea_produccion', 'producto', 'turno', 'maquina',
   'eficiencia_pct', 'tasa_defectos_pct', 'causa_paro']]

print(f'⚠️ Órdenes con baja eficiencia y alta tasa de defectos: {len(baja_eficiencia)}')
baja_eficiencia.sort_values('eficiencia_pct')

"""## ✅ Autoevaluación

Verifica que completaste correctamente:
- [ ] Importaste las librerías
- [ ] Cargaste el CSV y convertiste la fecha
- [ ] Calculaste los 3 KPIs (eficiencia, unidades, paros)
- [ ] Creaste las 5 gráficas sin errores
- [ ] Identificaste las órdenes con baja eficiencia

Si todo funciona, ¡estás listo para el Caso 4! 🚀
"""